name: Test and Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Run unit tests
        run: npm run test
        env:
          CI: true

      - name: Setup Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-

      - name: Run E2E tests
        run: npx playwright install --with-deps && npm run test:e2e
        env:
          CI: true

      - name: Build production
        run: npm run build
        env:
          CI: true
